/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotindexRouteImport } from './routes/notindex'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProjectsRouteImport } from './routes/_authed/projects'
import { Route as AuthedMyLaneRouteImport } from './routes/_authed/my-lane'
import { Route as AuthedDiscoverRouteImport } from './routes/_authed/discover'

const NotindexRoute = NotindexRouteImport.update({
  id: '/notindex',
  path: '/notindex',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyLaneRoute = AuthedMyLaneRouteImport.update({
  id: '/my-lane',
  path: '/my-lane',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDiscoverRoute = AuthedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notindex': typeof NotindexRoute
  '/discover': typeof AuthedDiscoverRoute
  '/my-lane': typeof AuthedMyLaneRoute
  '/projects': typeof AuthedProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notindex': typeof NotindexRoute
  '/discover': typeof AuthedDiscoverRoute
  '/my-lane': typeof AuthedMyLaneRoute
  '/projects': typeof AuthedProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/notindex': typeof NotindexRoute
  '/_authed/discover': typeof AuthedDiscoverRoute
  '/_authed/my-lane': typeof AuthedMyLaneRoute
  '/_authed/projects': typeof AuthedProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notindex' | '/discover' | '/my-lane' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notindex' | '/discover' | '/my-lane' | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/notindex'
    | '/_authed/discover'
    | '/_authed/my-lane'
    | '/_authed/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  NotindexRoute: typeof NotindexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notindex': {
      id: '/notindex'
      path: '/notindex'
      fullPath: '/notindex'
      preLoaderRoute: typeof NotindexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-lane': {
      id: '/_authed/my-lane'
      path: '/my-lane'
      fullPath: '/my-lane'
      preLoaderRoute: typeof AuthedMyLaneRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/discover': {
      id: '/_authed/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthedDiscoverRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDiscoverRoute: typeof AuthedDiscoverRoute
  AuthedMyLaneRoute: typeof AuthedMyLaneRoute
  AuthedProjectsRoute: typeof AuthedProjectsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDiscoverRoute: AuthedDiscoverRoute,
  AuthedMyLaneRoute: AuthedMyLaneRoute,
  AuthedProjectsRoute: AuthedProjectsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  NotindexRoute: NotindexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
